import { useState } from "react";
import Modal from "../components/Modal";
import Button from "../components/Button";

function ModalPage() {

    const [showModal, setShowModal] = useState(false);

    const handleClick = () => {
        setShowModal(true);
    }
    const handleClose = () => {
        setShowModal(false);
    }

    const actionBar = <div><Button onClick={handleClose} primary>Accept</Button></div>

    const modal = <Modal onClose={handleClose} actionBar={actionBar}>
        <p>Here is something inside the modal</p>
    </Modal>

    return (
        <div className="relative">
            <Button onClick={handleClick} primary>
                Open Modal
            </Button>
            {showModal && modal}
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque dignissim enim at ultricies. Nullam vitae rutrum augue, ac condimentum erat. Curabitur sed ex lacus. Pellentesque semper, orci sed tempor finibus, lectus quam venenatis ex, dignissim lobortis quam metus vel neque. Aenean ut scelerisque sem, non finibus nibh. Aliquam mi dolor, vehicula ultricies urna vitae, suscipit pretium nunc. Curabitur vitae tellus id quam tempus viverra vel sit amet urna. Maecenas a urna semper, finibus magna eget, lobortis metus. Nam lobortis lorem nisi, at hendrerit augue ornare eget. Vestibulum sed felis ligula. Nam iaculis efficitur consectetur. Vestibulum mollis mi id felis commodo facilisis vitae eu nisi. Sed nec eleifend neque. Donec massa sem, dignissim nec quam ut, ullamcorper tincidunt lorem. Pellentesque aliquam nisi ut rutrum dignissim. Mauris a lorem nec erat placerat tristique sit amet ac quam.</p>
        </div>
    )
}

export default ModalPage;